const tintPrimaryColorDark = "#cc4300";
const tintPrimaryColorDarkDarker = "#c54100";
const tintPrimaryColorDarkLighter = "#ff9800";
const tintSecondaryColorDark = "#2b2b4c";
const tintPrimaryColorLight = "#FF5500";
const tintPrimaryColorLightDarker = "#7f2a00";
const tintPrimaryColorLightLighter = "#ff9800";
const tintSecondaryColorLight = "#34345B";

export const darkTheme = {
  mode: "dark",
  PRIMARY_GENERAL_COLOR: tintPrimaryColorDark,
  GRADIENT_COLORS: {
    normal: tintPrimaryColorDark,
    darker: tintPrimaryColorDarkDarker,
    lighter: tintPrimaryColorDarkLighter,
    themed: tintPrimaryColorDarkDarker,
  },
  SECONDARY_GENERAL_COLOR: tintSecondaryColorDark,
  PRIMARY_BACKGROUND_COLOR: "#191919",
  PRIMARY_TEXT_COLOR: "#ABABAB",
  PRIMARY_TEXT_MENU_COLOR: "#e0e0e0",
  PRIMARY_TITLE_COLOR: "#fff",
  IMAGE_STROKE_COLOR: "#fff",
  INPUT_BACKGROUND_COLOR: "#191919",
  PLACEHOLDER_TEXT_COLOR: "#a7a7a7",
  PLACEHOLDER_TEXT_ERROR_COLOR: "#ee9f9f",
  SECONDARY_TEXT_COLOR: "#fff",
  PRIMARY_BUTTON_COLOR: tintPrimaryColorDark,
  PRIMARY_BUTTON_ACTIVE_COLOR: "#fff",
  PRIMARY_BUTTON_NOT_ACTIVE_COLOR: "#bfbfbf",
  SECONDARY_BUTTON_ACTIVE_COLOR: "#303030",
  BUTTON_TEXT_ACTIVE_COLOR: "#e0e0e0",
  BUTTON_TEXT_NOT_ACTIVE_COLOR: "#fff",
  BUTTON_ONLY_TEXT_COLOR: "#878787",
  PRIMARY_BORDER_COLOR: "#2e2e2e",
  BORDER_ERROR_COLOR: "#ee9f9f",
  PRIMARY_MENU_BACKGROUND_COLOR: tintPrimaryColorDark,
  PRIMARY_TAB_COLOR: tintPrimaryColorDark,
  PRIMARY_TAB_SELECTED_COLOR: "#E8E8E8",
  PRIMARY_ICON_COLOR: "#000",
  PRIMARY_ICON_ACTIVE_COLOR: tintPrimaryColorDark,
  PRIMARY_ERROR_COLOR: "#ff5e5e",
  PRIMARY_SUCCESS_COLOR: "#00ff00",
  CARD_BACKGROUND_COLOR: "#212121",
  TABLE_HEADER_BACKGROUND_COLOR: "#181818",
  TABLE_CELL_BACKGROUND_COLOR: "#181818",
  STATUS_BAR_STYLE: "light-content",
};

export const lightTheme = {
  mode: "light",
  PRIMARY_GENERAL_COLOR: tintPrimaryColorLight,
  GRADIENT_COLORS: {
    normal: tintPrimaryColorLight,
    darker: tintPrimaryColorLightDarker,
    lighter: tintPrimaryColorLightLighter,
    themed: tintPrimaryColorLightLighter,
  },
  SECONDARY_GENERAL_COLOR: tintSecondaryColorLight,
  PRIMARY_BACKGROUND_COLOR: "#fff",
  PRIMARY_TEXT_COLOR: "#000",
  PRIMARY_TEXT_MENU_COLOR: "#fff",
  PRIMARY_TITLE_COLOR: "#000",
  IMAGE_STROKE_COLOR: tintPrimaryColorLight,
  INPUT_BACKGROUND_COLOR: "#FFF",
  PLACEHOLDER_TEXT_COLOR: "#A4A4A4",
  PLACEHOLDER_TEXT_ERROR_COLOR: "#ff5e5e",
  SECONDARY_TEXT_COLOR: tintPrimaryColorLight,
  PRIMARY_BUTTON_COLOR: tintPrimaryColorLight,
  PRIMARY_BUTTON_ACTIVE_COLOR: tintPrimaryColorLight,
  PRIMARY_BUTTON_NOT_ACTIVE_COLOR: "black",
  SECONDARY_BUTTON_ACTIVE_COLOR: "#303030",
  BUTTON_TEXT_ACTIVE_COLOR: "#fff",
  BUTTON_TEXT_NOT_ACTIVE_COLOR: tintPrimaryColorDark,
  BUTTON_ONLY_TEXT_COLOR: "#727272",
  PRIMARY_BORDER_COLOR: "#727272",
  BORDER_ERROR_COLOR: "#ff5e5e",
  PRIMARY_MENU_BACKGROUND_COLOR: tintPrimaryColorLight,
  PRIMARY_TAB_COLOR: tintPrimaryColorLight,
  PRIMARY_TAB_SELECTED_COLOR: "#E8E8E8",
  PRIMARY_ICON_COLOR: "#fff",
  PRIMARY_ICON_ACTIVE_COLOR: tintPrimaryColorLight,
  PRIMARY_ERROR_COLOR: "#ff5e5e",
  PRIMARY_SUCCESS_COLOR: "#00ff00",
  CARD_BACKGROUND_COLOR: "#fafafa",
  TABLE_HEADER_BACKGROUND_COLOR: "#fff",
  TABLE_CELL_BACKGROUND_COLOR: "#fff",
  STATUS_BAR_STYLE: "dark-content",
};
